version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: remember_bot_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d remember_bot_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      TELEGRAM_BOT_API_KEY: ${TELEGRAM_BOT_API_KEY}
      POSTGRESQL_DATABASE_URL: postgresql+asyncpg://admin:admin@db:5432/remember_bot_db
      SECRET_JWT_KEY: ${SECRET_JWT_KEY}
    ports:
      - "8000:8000"

    restart: unless-stopped

volumes:
  postgres_data: